spring:
  application:
    name: pharma-order-processor
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartpharmadb?searchpath=oms_schema
    username: postgres
    password: admin
  jpa:
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect    
server:
  port: 8081
  servlet:
    context-path: /pharma  
app:
  config:
    aws:
      region: ap-south-1
      access-key-id: 
      secret-key-id: 
    message:
      queue:
        topic: order-queue
springdoc:
  api-docs:
    path: /swagger-ui.html  